
locale: "en-US"
title: "Taun Parshall Chapman"
title_separator: "-"
subtitle: "Welcome"
email: "website@charcoalia.net"
description: "Strategist, Philomath, Problem Solver, Proven Innovator, Empathizer, Coach, Mentor"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.taun.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter: taunc
repository:  taun

author:
  name     : "Taun Parshall Chapman"
  avatar   : "/assets/images/TaunHeadShotSpaces180.png"
  bio      : "Strategist, Philomath, Problem Solver, Proven Innovator, Empathizer, Coach, Mentor"
  location : "East Coast, USA"
  links:
      - label: "Twitter"
        icon: "fab fa-fw fa-twitter-square"
        url: "https://twitter.com/taunc"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/taun"
      - label: "Instagram"
        icon: "fab fa-fw fa-instagram"
        url: "https://instagram.com/taunpc"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"
breadcrumbs: true
search: true

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  project:
    output: true
    permalink: /:collection/:path/
    
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/taunc"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/taun"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/taunpc"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio, work down for hire
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
      header:
        teaser: /assets/images/project_background.png
  # _project, side projects & fun stuff
  - scope:
      path: ""
      type: project
    values:
      layout: single
      author_profile: false
      share: true
      header:
        teaser: /assets/images/project_background.png

plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - .htaccess
  - _pages
  - _posts
  - _project
  - _portfolio

keep_files:
  - .git

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
